version: '3'

services:
  app:
    image: spotify-radio
    build: .
    command: npm run live-reload
    environment:
      PORT: 3000
    volumes: 
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

volumes: 
  node_modules: {}